### PR TITLE
CP-16094: ocaml-xenstore-clients: Install xstest in %{_libexecdir}

### PR DESCRIPTION
**Pull request by jjd27**

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
Yeah sorry about that. I guess the autogen makefile just uses BINDIR now...

**Comment by simonjbeaumont** [comment]
But I don't think we want it here... /opt/xensource/debug is a no-no... we're now being good packaging citizens and we should put stuff in good places according to the FHS.

**Comment by simonjbeaumont** [comment]
perhaps /usr/libexec? take a look at the fedora packaging guidelines or some of the other spec files (that aren't xapi -- that's rubbish).

**Comment by simonjbeaumont** [comment]
Basically anything that actually exists in the RPM macros is probably ok... e.g. %{libexecdir}. Just choose the most sane one based on the descriptions in FHS.

**Comment by jjd27** [comment]
Fair enough. I was merely following suit with things that seemed similar in spirit to this, e.g. quicktest, perftest. I'll change it to install into %{_libexecdir}.

**Comment by simonjbeaumont** [comment]
You'll hate me for this but there's obviously a problem with the commit message now :)

**Comment by jjd27** [comment]
Not at all. I can't believe I missed that!

**Comment by simonjbeaumont** [comment]
Looks good. I'll merge it when the build succeeds.

**Comment by simonjbeaumont** [comment]
@xen-git retest this please.

**Comment by robhoes** [comment]
I'll merge this now that Si has acked it and the build has succeeded.

**Pull request merged**
